osx_image: xcode7.3,
language: node_js
sudo: false
git:
  depth: 10
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
before_install:
  - rvm install 2.0.0
  - gem install activesupport -v '4.2.6'
  - gem install cocoapods -v '1.0.1'
install:
  - git clone https://github.com/apache/cordova-js --depth 10
  - cd cordova-lib
  - npm link ../cordova-js
  - npm link ../cordova-common
  - npm link ../cordova-serve
  - (cd ../cordova-fetch && npm link ../cordova-common && npm install)
  - npm link ../cordova-fetch
  - npm install
  # Workaround for npm/npm#10343 when dependency of linked module is moved to dependent
  # module's 'node_modules' In our case 'cordova-common' -> jshint' -> 'cli' dependency
  # is moved to 'cordova-lib' and hence 'npm run jshint' on 'cordova-common' is failing
  - "(cd ../cordova-common && npm install)"
  - (cd ../cordova-fetch && npm install && npm link ../cordova-common)

script:
  - "(cd ../cordova-common && npm test)"
  - "(cd ../cordova-fetch && npm test)"
  - "npm run ci-ios"
