# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

install:
  - cd ..
  - git clone https://github.com/apache/cordova-js --depth 10
  - cd cordova-js
  - npm install --msvs_version=2013
  - npm link
  - cd ..\cordova-lib\cordova-lib
  - npm link cordova-js
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm test
